attribute_means:
  elev_mean: 715.0357281553398
  slope_mean: 45.73078805825243
attribute_stds:
  elev_mean: 772.9868594812874
  slope_mean: 46.97479379837598
xarray_feature_center:
  attrs: {}
  coords: {}
  data_vars:
    APCP_surface:
      attrs: {}
      data: 0.1423874795436859
      dims: []
    DLWRF_surface:
      attrs: {}
      data: 303.1827697753906
      dims: []
    DSWRF_surface:
      attrs: {}
      data: 188.4970245361328
      dims: []
    PRES_surface:
      attrs: {}
      data: 92957.4453125
      dims: []
    QObs(mm/h):
      attrs: {}
      data: 0.07123023271560669
      dims: []
    SPFH_2maboveground:
      attrs: {}
      data: 0.007006556261330843
      dims: []
    TMP_2maboveground:
      attrs: {}
      data: 283.87200927734375
      dims: []
    UGRD_10maboveground:
      attrs: {}
      data: 0.97260981798172
      dims: []
    VGRD_10maboveground:
      attrs: {}
      data: 0.4705375134944916
      dims: []
  dims: {}
xarray_feature_scale:
  attrs: {}
  coords: {}
  data_vars:
    APCP_surface:
      attrs: {}
      data: 0.8294922113418579
      dims: []
    DLWRF_surface:
      attrs: {}
      data: 149.94964599609375
      dims: []
    DSWRF_surface:
      attrs: {}
      data: 226.2925262451172
      dims: []
    PRES_surface:
      attrs: {}
      data: 35709.50390625
      dims: []
    QObs(mm/h):
      attrs: {}
      data: 0.16732385754585266
      dims: []
    SPFH_2maboveground:
      attrs: {}
      data: 0.005186231806874275
      dims: []
    TMP_2maboveground:
      attrs: {}
      data: 98.63380432128906
      dims: []
    UGRD_10maboveground:
      attrs: {}
      data: 2.5150809288024902
      dims: []
    VGRD_10maboveground:
      attrs: {}
      data: 2.7686984539031982
      dims: []
  dims: {}
